#!/bin/bash -l
#PBS -N FluxTube 
# request 1 cpu:
#PBS -l nodes=1:ppn=1
# request it for 120 minutes:
#PBS -l walltime=00:59:00
# cd to the directory from which qsub is run:
#PBS -A default_project 
#PBS -M michaela.brchnelova@kuleuven.be

cd $PBS_O_WORKDIR

python icosphere_pure_triple.py icosub5.ply level5_triple.brch
#python icosphere_pure.py icosub5.ply level5_full.brch
#python icosphere_pure.py icosub6.ply level6_full.brch 
